name: Py Scraper 
on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  scraper:
    name: Py Scraper 
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@main
        with:
          python-version: 3.11

      - name: Cache Python packages
        uses: actions/cache@main
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: | 
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install -r requirements.txt
          
      - name: Scraper 
        run: python main.py
        
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
