name: Py Scraper 
on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  scraper:
    name: Py Scraper 
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@main
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Scraper 
        run: python -m src
        
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
