name: Py Scraper

on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  scraper:
    name: Py Scraper 
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0
    
      - name: Install WARP/WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wireguard-tools
          
          # Download WARP keys from Cloudflare
          curl https://pkg.cloudflareclient.com/pubkey.gpg | sudo apt-key add -
          echo 'deb http://pkg.cloudflareclient.com/ bionic main' | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
          
          # Install WARP client
          sudo apt-get update
          sudo apt-get install -y cloudflare-warp

      - name: Connect to Warp
        run: |
          # Enable Warp
          sudo warp-cli register
          sudo warp-cli connect

      - name: Verify Warp Connection
        run: curl https://www.cloudflare.com/cdn-cgi/trace | grep warp

      - name: Install Python
        uses: actions/setup-python@main
        with:
          python-version: 3.11

      - name: Cache Python packages
        uses: actions/cache@main
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: pip install -r requirements.txt
          
      - name: Scraper 
        run: python main.py
        
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
